### ISSUE TITLE
domain error when computing on experimental data

### ISSUE THREAD

**Issue by jianzuo** [ciuccislab/pyDRTtools#11]
Hi,
I have tried to fit an experimental data 
[check_T1016.csv](https://github.com/ciuccislab/pyDRTtools/files/14028182/check_T1016.csv)
, but the GUI was force to quit with error message:
```
IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  out_val = integrate.quad(integrand_g_ii, -50, 50, epsabs=1E-9, epsrel=1E-9)
Inequality constraints incompatible    (Exit mode 4)
            Current function value: nan
            Iterations: 1
            Function evaluations: 2
            Gradient evaluations: 1
GCV
     pcost       dcost       gap    pres   dres
 0:      nan      nan  nan  0e+00    nan
Traceback (most recent call last):
  File "/home/zuoj/FC_model_estimation/pyDRTtools-master/pyDRTtools/GUI.py", line 119, in simple_run_callback
    self.data = simple_run(self.data, rbf_type = rbf_type, data_used = data_used, induct_used = induct_used,
  File "/home/zuoj/FC_model_estimation/pyDRTtools-master/pyDRTtools/runs.py", line 192, in simple_run
    x = basics.cvxopt_solve_qpr(H_combined, c_combined,-bound_mat,lb) # using cvxopt
  File "/home/zuoj/FC_model_estimation/pyDRTtools-master/pyDRTtools/basics.py", line 803, in cvxopt_solve_qpr
    sol = cvxopt.solvers.qp(*args)
  File "/home/zuoj/anaconda3_2022/envs/torch2/lib/python3.9/site-packages/cvxopt/coneprog.py", line 4485, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "/home/zuoj/anaconda3_2022/envs/torch2/lib/python3.9/site-packages/cvxopt/coneprog.py", line 2243, in coneqp
    if iters == 0:  W = misc.compute_scaling(s, z, lmbda, dims)
  File "/home/zuoj/anaconda3_2022/envs/torch2/lib/python3.9/site-packages/cvxopt/misc.py", line 285, in compute_scaling
    W['d'] = base.sqrt( base.div( s[mnl:mnl+m], z[mnl:mnl+m] ))
ValueError: domain error
Aborted (core dumped)
```

My calculation settings are: 
![drt_self2](https://github.com/ciuccislab/pyDRTtools/assets/39144149/ea04a701-fe4a-4053-93a8-b8312a3a1815)

By the way, is it possible to have an API version of the pyDRTtool? Then, it might be more convenient to compute with multiple data files and probably easier for debugging. 

Thank you very much for checking!

**Comment by jianzuo** [comment]
I have tried to delete **the fourth-row** of the original data file and the DRT was computed without an error. 
But I didn't see what's the cause of the above error.

**Comment by ciuccislab** [comment]
Thank you for your interest in pyDRTtools. Did you delete the high frequency part of the data? (Just to clarify about the deleted fourth-row you mentioned), and thank you for the suggestion.

**Comment by jianzuo** [comment]
Yes, it is the high-frequency row, see below:
![d1](https://github.com/ciuccislab/pyDRTtools/assets/39144149/1c706c10-6edb-440e-a478-d2484045d173)
 
Thank you!
